// <auto-generated />
using System;
using LeagueManagementAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LeagueManagementAPI.Migrations
{
    [DbContext(typeof(LeagueManagementContext))]
    [Migration("20200823055648_PeopleMigration2")]
    partial class PeopleMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LeagueManagementAPI.Data.Enttities.address", b =>
                {
                    b.Property<int>("address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("apartment_number")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("zip_code_id")
                        .HasColumnType("integer");

                    b.HasKey("address_id");

                    b.ToTable("address");
                });

            modelBuilder.Entity("LeagueManagementAPI.Data.Enttities.child", b =>
                {
                    b.Property<int>("child_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("child_id");

                    b.ToTable("child");
                });

            modelBuilder.Entity("LeagueManagementAPI.Data.Enttities.login", b =>
                {
                    b.Property<int>("login_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("last_update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("parent_id")
                        .HasColumnType("integer");

                    b.Property<string>("password_hash")
                        .HasColumnType("text");

                    b.Property<string>("password_hash_algorithm")
                        .HasColumnType("text");

                    b.Property<string>("password_salt")
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("login_id");

                    b.ToTable("login");
                });

            modelBuilder.Entity("LeagueManagementAPI.Data.Enttities.parent", b =>
                {
                    b.Property<int>("parent_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("address_id")
                        .HasColumnType("integer");

                    b.Property<int>("email")
                        .HasColumnType("integer");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("parent_id");

                    b.ToTable("parent");
                });

            modelBuilder.Entity("LeagueManagementAPI.Data.Enttities.parent_child", b =>
                {
                    b.Property<int>("parent_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("child_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("parent_id");

                    b.ToTable("parent_child");
                });

            modelBuilder.Entity("LeagueManagementAPI.Data.Enttities.zip_code", b =>
                {
                    b.Property<int>("zip_code_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("county_name")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_update")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("latitude")
                        .HasColumnType("integer");

                    b.Property<int>("longitude")
                        .HasColumnType("integer");

                    b.Property<int>("population")
                        .HasColumnType("integer");

                    b.Property<string>("postal_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("state_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("state_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("timezone")
                        .HasColumnType("text");

                    b.HasKey("zip_code_id");

                    b.ToTable("zip_code");
                });
#pragma warning restore 612, 618
        }
    }
}
